### ISSUE TITLE
Include iFixes & Features with SBOM information

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/liberty#137]
## What happened?

* What were you attempting to do?
When building an app, the buildpack generates SBOM information. This does not presently include information about applied iFixes or additional Features that have been installed.

* What did you expect to happen?

Add some indication that iFixes have been applied and that Features have been installed as this can impact whether a generated image is vulnerable to security issues.

It is unclear exactly how this information would need to be represented in the SBOM metadata such that security scanners like [Grype](https://github.com/anchore/grype/) are able to report on the information in a meaningful way. More investigation needs to be done before changes an be made.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by kevin-ortega** [comment]
`wlp\bin\productInfo version --ifixes` will provide a list of applied iFixes.  I don't think it's typical that an a specific iFix would be declared vulnerable.  Usually (always?) liberty will declare a specific feature vulnerable.  

To get a list of installed features we can use:
```
cnb@17a1ba939c97:/layers/paketo-buildpacks_liberty/open-liberty-runtime-full$ bin/productInfo featureInfo
acmeCA-2.0
adminCenter-1.0
appClientSupport-1.0
appSecurity-1.0
appSecurity-2.0
appSecurity-3.0
appSecurityClient-1.0
.
.
.
```
