### ISSUE TITLE
The image built by paketo with kernel profile does not work 

### ISSUE THREAD

**Issue by gkwan-ibm** [paketo-buildpacks/liberty#201]
The image built by paketo with kernel profile does not work.

## Expected Behavior
works

## Current Behavior
not work

## Steps to Reproduce
- `git clone https://github.com/uhryniuk/draft-guide-containerize-paketo.git`
- `cd draft-guide-containerize-paketo/finish`
- `mvn package`

### scenario 1
- run following command:
```
pack build \
--env BP_JAVA_APP_SERVER=liberty \
--env BP_MAVEN_BUILT_ARTIFACT="target/*.war src/main/liberty/config/*" \
--env BP_LIBERTY_PROFILE=kernel \
--env BP_LIBERTY_FEATURES="cdi-3.0 jsonb-2.0 jsonp-2.0 restfulWS-3.0 jsp-2.3" \
--buildpack paketo-buildpacks/eclipse-openj9 \
--buildpack paketo-buildpacks/java \
--creation-time now \
system:1.0-SNAPSHOT
```
- `docker run --rm -d --name system -p 9080:9080 system:1.0-SNAPSHOT`
- visit http://localhost:9080 and have no response because the server cannot be started 
- `docker logs system` and will get the following error. Most likely the buildpacks installed incorrect set of features
```
{"type":"liberty_message","host":"0c3568ee7a48","ibm_userDir":"\/layers\/paketo-buildpacks_liberty\/open-liberty-runtime-kernel\/usr\/","ibm_serverName":"defaultServer","message":"CWWKF0033E: The singleton features io.openliberty.servlet.api-5.0 and io.openliberty.servlet.api-3.0 cannot be loaded at the same time.  The configured features restfulWS-3.0 and restfulWS-3.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.","ibm_threadId":"0000002c","ibm_datetime":"2022-07-18T19:34:41.498+0000","ibm_messageId":"CWWKF0033E","module":"com.ibm.ws.kernel.feature.internal.FeatureManager","loglevel":"ERROR","ibm_sequence":"1658172881498_0000000000005"}
```

### scenario 2
- run following command by this [recommendation](https://github.com/paketo-buildpacks/liberty/issues/183#issuecomment-1179346434) (not using `BP_MAVEN_BUILT_ARTIFACT`):
```
pack build \
--env BP_JAVA_APP_SERVER=liberty \
--env BP_LIBERTY_PROFILE=kernel \
--env BP_LIBERTY_FEATURES="cdi-3.0 jsonb-2.0 jsonp-2.0 restfulWS-3.0 jsp-2.3" \
--buildpack paketo-buildpacks/eclipse-openj9 \
--buildpack paketo-buildpacks/java \
--creation-time now \
system:1.0-SNAPSHOT
```
- `docker run --rm -d --name system -p 9080:9080 system:1.0-SNAPSHOT`
- visit http://localhost:9080 and should have no problem
- visit http://localhost:9080/system/properties and will get error
  - `Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /system/properties `
- run `docker exec -it system cat /layers/paketo-buildpacks_liberty/open-liberty-runtime-kernel/usr/servers/defaultServer/server.xml`. I found the server.xml is not from `finish/src/main/liberty/config/server.xml`
- surely the recommendation is not the solution.

## Motivations
We are writing an introduction guide but paketo buildpack does not work as expected

**Comment by hibell** [comment]
Hello @gkwan-ibm. This issue should be resolved after #200.

**Comment by dmikusa-pivotal** [comment]
FYI, #200 has been merged. Version 2.0.0 of the Liberty buildpack has these changes.

**Comment by kevin-ortega** [comment]
Closing.  This issue is fixed.

**Comment by kevin-ortega** [comment]
This issue is fixed.
