### ISSUE TITLE
Not compliant with new stricter security settings

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-buildpacks/liberty#70]
There are stricter security settings coming with buildpacks. Right now, when you build the user/group is `cnb`/`cnb`. This is how files are written to disk. Right now, when you run the default is to run as `cnb`/`cnb`. This means the user can write to files written by the buildpack and can write to the `/workspace`.

Going forward, buildpacks will still build as the same user but will run as a different user (not sure the name) but the same group, so for example `foo` / `cnb`. This means that at run time you won't be able to write to the `/layers` or `/workspace` directory, unless you specifically give those locations group-write access.

I believe that our `helper/linker.go` is going to be impacted by this. It's writing symlinks and copying config files out of bindings.

The options to correct this and make it compliant are:

1. Move code that writes files to happen at build time. You can't really do that with bindings, but perhaps the stuff being done with features in there could move to build time.
2. At build time, make any directories that need to be written to at run time group writable. It should be as limited of a set as possible.

I also wonder if the Open Liberty server makes any assumptions about being able to write files? Does it need to write temp file or logs? We should try to write those to `/tmp` if possible, or again, make the directories where they write to group write.

**Comment by kevin-ortega** [comment]
@dmikusa-pivotal is this required for the v1.0 release?

**Comment by dmikusa-pivotal** [comment]
I would say no because that is an upcoming change. We could implement it now, but it's not required quite yet.
